name: Test Merge Commit
on: pull_request

jobs:
    test-merge:
        runs-on: ${{ matrix.config.os }}
        strategy:
            matrix:
                config:
                    # arch isn't used and we have no way to use it currently
                    - { os: macos-latest, arch: x64 }
                    - { os: ubuntu-latest, arch: x64 }
                    - { os: windows-latest, arch: x64 }
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
            - run: npm install --build-from-source
            - run: npm run tsc
            - run: npm run test
