name: Test Merge Commit
on: pull_request

jobs:
  test-merge:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        config:
          # arch isn't used and we have no way to use it currently
          - { os: macos-latest, arch: x64 }
          - { os: ubuntu-latest, arch: x64 }
          - { os: windows-latest, arch: x64 }
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"
      - run: npm install --build-from-source
      - run: npm run tsc
      - run: npm run test
